const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=v=>v===null||v===undefined?'N/A':`${(v*100).toFixed(1)}%`;
const num=v=>Number(v||0).toLocaleString('en-IN');
const INR=v=>'₹'+num(Math.round(v));
async function api(path,method='GET',data){let options={method,headers:{'Content-Type':'application/json'}};if(data!==undefined)options.body=JSON.stringify(data);let resp=await fetch(path,options);let result=await resp.json();if(!resp.ok)throw new Error(result.detail||result.error||resp.statusText);return result}
function busy(button,yes){button.disabled=yes;button.dataset.original??=button.textContent;button.textContent=yes?'Processing…':button.dataset.original}
function setPage(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#crumb').textContent=page.replaceAll('_',' ').toUpperCase();if(page==='audit')loadAudit();if(page==='evaluation')loadMetrics();if(page==='evidence')loadEvidence();}
$$('.nav').forEach(x=>x.onclick=()=>setPage(x.dataset.page));
const request=()=>({content:$('#content').value,source_type:$('#source').value,role:$('#role').value,task:$('#task').value,force_fallback:$('#forceFallback').checked});
let allScenarios=[];
async function initialize(){try{let data=await api('/scenarios');allScenarios=data.scenarios;$('#scenario').innerHTML=allScenarios.map(x=>`<option value="${safe(x.id)}">${safe(x.title)} · ${safe(x.kind)}</option>`).join('');selectScenario();let health=await api('/health');$('#llmState').textContent=health.llm_configured?'LLM KEY CONFIGURED':health.local_ml_enabled?'OFFLINE HYBRID ML':'OFFLINE HEURISTIC MODE';}catch(e){alert('Server not reachable: '+e.message)}}
function selectScenario(){let s=allScenarios.find(x=>x.id===$('#scenario').value)||allScenarios[0];if(!s)return;$('#content').value=s.content;$('#source').value=s.source_type;$('#inspectionResult').classList.add('hide');$('#emptyResult').classList.remove('hide');$('#disposition').textContent='AWAITING INPUT';$('#disposition').className='status neutral';$('#comparison').classList.add('hide')}
$('#scenario').addEventListener('change',selectScenario);
$('#upload').onchange=async e=>{let f=e.target.files[0];if(!f)return;let data=new FormData();data.append('file',f);try{let response=await fetch('/ingest/file',{method:'POST',body:data});let obj=await response.json();if(!response.ok)throw new Error(obj.detail||obj.error||'Upload error');$('#content').value=obj.content;$('#source').value=obj.source_type;alert(`Loaded ${obj.filename}: ${obj.characters} characters${obj.truncated?' (truncated)':''}`)}catch(err){alert(err.message)}};
function showInspection(d){$('#emptyResult').classList.add('hide');$('#inspectionResult').classList.remove('hide');$('#disposition').textContent=d.disposition;$('#disposition').className=`status ${d.malicious?'danger':'good'}`;$('#severity').textContent=d.severity.toUpperCase();$('#classifier').textContent=d.model.replaceAll('_',' ');$('#scanTime').textContent=d.latency_ms+' ms';$('#rationale').textContent=d.rationale;$('#sha').textContent=d.source_sha256;$('#categories').innerHTML=(d.categories.length?d.categories:['No detected attack']).map(x=>`<span class="tag">${safe(x)}</span>`).join('');$('#evidenceSpans').innerHTML=d.evidence.length?d.evidence.map(x=>`<div class="span"><b>${safe(x.category)}</b> · ${safe(x.excerpt)}</div>`).join(''):'<div class="muted">No suspicious span captured.</div>';}
$('#scanBtn').onclick=async()=>{let b=$('#scanBtn');busy(b,true);try{let d=await api('/scan','POST',request());showInspection(d)}catch(e){alert(e.message)}finally{busy(b,false)}};
function executionHTML(r){let tag=r.attack_success?'<b class="bad">YES — scripted violation</b>':'<b class="ok">NO</b>';return `<div class="scoreline"><div><small>TASK COMPLETED</small><strong class="${r.task_completed?'ok':'bad'}">${r.task_completed?'YES':'NO'}</strong></div><div><small>ATTACK SUCCESS</small><strong>${tag}</strong></div><div><small>DENIED ATTEMPTS</small><strong>${r.denied_actions.length}</strong></div></div><div class="field"><label>Mock tool actions</label><div class="execution-list">${r.tool_actions.map(a=>`<div class="execution-item"><strong>${safe(a.tool)}</strong><span>${safe(a.result).substring(0,74)}</span></div>`).join('')}</div></div>${r.denied_actions.length?`<div class="field"><label>Blocked by policy</label><div class="execution-list">${r.denied_actions.map(a=>`<div class="execution-item"><strong class="bad">${safe(a.tool)}</strong><span>${safe(a.rule)}</span></div>`).join('')}</div></div>`:''}<div class="field"><label>Agent response</label><div class="answer">${safe(r.answer)}</div></div><div class="hash">RUN ID · ${safe(r.run_id)}</div>`}
$('#compareBtn').onclick=async()=>{let b=$('#compareBtn');busy(b,true);try{let x=await api('/agent/compare','POST',request());showInspection(x.protected.inspection);$('#baselineData').innerHTML=executionHTML(x.baseline);$('#protectedData').innerHTML=executionHTML(x.protected);$('#comparison').classList.remove('hide');$('#comparison').scrollIntoView({behavior:'smooth',block:'nearest'})}catch(e){alert(e.message)}finally{busy(b,false)}};
function metricCard(label,value,note){return `<div><small>${safe(label)}</small><strong>${safe(value)}</strong><em>${safe(note)}</em></div>`}
async function loadMetrics(){try{let m=await api('/metrics');if(!m.total_cases){$('#metricCards').innerHTML='<div class="muted">Click Run held-out benchmark to generate real results.</div>';return}$('#metricCards').innerHTML=metricCard('MALICIOUS RECALL',pct(m.recall),`${m.attack_cases} attack samples`)+metricCard('DETECTION PRECISION',pct(m.precision),`${m.tp} true positives`)+metricCard('FALSE-POSITIVE RATE',pct(m.false_positive_rate),`${m.benign_and_ambiguous_cases} nonattack cases`)+metricCard('BENIGN TASK UTILITY',pct(m.protected_benign_task_completion_rate),'Protected sandbox')+metricCard('PROTECTED ASR',pct(m.protected_attack_success_rate),'Tool effects actually measured')+metricCard('SCRIPTED CONTROL ASR',pct(m.scripted_baseline_attack_success_rate),'Not a real LLM baseline')+metricCard('FORBIDDEN EXECUTIONS',m.unauthorized_protected_tool_executions,`${m.denied_tool_attempts} attempts denied`)+metricCard('P95 SCAN LATENCY',m.p95_scan_ms+' ms','Local offline heuristic');$('#confusion').innerHTML=`<div class="matrix"><div><small>TRUE POSITIVE</small><b class="ok">${m.tp}</b></div><div><small>FALSE NEGATIVE</small><b class="bad">${m.fn}</b></div><div><small>FALSE POSITIVE</small><b class="bad">${m.fp}</b></div><div><small>TRUE NEGATIVE</small><b class="ok">${m.tn}</b></div></div><p class="muted">F1: ${pct(m.f1)} · Split: ${safe(m.split)} · Cases: ${m.total_cases}</p>`;$('#catMetrics').innerHTML=Object.entries(m.per_category).map(([name,v])=>`<div class="bar-row"><div class="bar-head"><span>${safe(name)}</span><span>${pct(v.recall)} (${v.detected}/${v.cases})</span></div><div class="bar"><i style="width:${v.recall*100}%"></i></div></div>`).join('')+'<p class="muted">Synthetic data: category success is not proof against new adversarial strategies.</p>'}catch(e){$('#metricCards').textContent=e.message}}
$('#evalBtn').onclick=async()=>{let b=$('#evalBtn');busy(b,true);try{await api('/evaluate?split=heldout','POST');await loadMetrics()}catch(e){alert(e.message)}finally{busy(b,false)}};
async function loadAudit(){try{let d=await api('/audit/recent');$('#auditList').innerHTML=d.runs.length?d.runs.map(r=>`<button class="trace-select" data-run="${safe(r.run_id)}">${safe(r.run_id).substring(0,16)}... <br/><small>${safe(r.timestamp)} · ${r.events} events</small></button>`).join(''):'<p class="muted">No audit traces yet. Run an Attack Lab scenario.</p>';$$('[data-run]').forEach(x=>x.onclick=()=>loadTrace(x.dataset.run));if(d.runs.length)loadTrace(d.runs[0].run_id)}catch(e){$('#auditList').textContent=e.message}}
async function loadTrace(id){let d=await api('/traces/'+encodeURIComponent(id));$('#auditDetail').innerHTML=`<p class="hash">${safe(id)}</p>`+d.events.map(e=>`<div class="trace-item"><strong>${safe(e.state)}</strong><small>${safe(e.timestamp)}</small><pre>${safe(JSON.stringify(Object.fromEntries(Object.entries(e).filter(([k])=>!['timestamp','state'].includes(k))),null,2))}</pre></div>`).join('')}
$('#refreshAudit').onclick=loadAudit;
async function loadEvidence(){let d=await api('/evidence');$('#evidenceTable').innerHTML=`<table class="evidence-table"><thead><tr><th>OFFICIAL ATTACK CATEGORY</th><th>HELD-OUT EXAMPLE IDs</th><th>EVIDENCE STATUS</th></tr></thead><tbody>${d.rows.map(x=>`<tr><td>${safe(x.category)}</td><td>${x.sample_ids.map(safe).join(', ')}</td><td>Pattern + evaluation</td></tr>`).join('')}</tbody></table>`}
const assumptions=[['monthly_requests','Monthly agent requests',100000,''],['risk_incident_rate','Incident probability per request',0.0001,'0.0001 = 0.01%'],['average_incident_cost','Average incident cost (INR)',250000,''],['assumed_risk_reduction','Assumed risk reduction',0.5,'0.5 = 50% (hypothetical)'],['manual_review_rate','Human review fraction',.02,''],['analyst_minutes','Minutes per review',4,''],['analyst_hourly_cost','Analyst cost / hour (INR)',800,''],['false_positive_review_rate','False-positive review fraction',.01,''],['estimated_monthly_platform_cost','Platform cost / month (INR)',20000,'']];
$('#impactInputs').innerHTML=assumptions.map(([key,label,value,unit])=>`<label>${safe(label)}<input id="imp_${key}" type="number" step="any" min="0" value="${value}"/><small>${safe(unit)}</small></label>`).join('');
$('#impactBtn').onclick=async()=>{let args=Object.fromEntries(assumptions.map(([key])=>[key,Number($('#imp_'+key).value)]));try{let r=await api('/impact','POST',args);$('#impactResults').innerHTML=`<small>HYPOTHETICAL NET MONTHLY BENEFIT</small><div class="impact-big">${INR(r.modeled_monthly_net_benefit_inr)}</div><div class="execution-list">${[['Expected baseline risk',r.baseline_monthly_expected_loss_inr],['Assumed incident loss avoided',r.assumed_monthly_loss_avoided_inr],['Analyst review cost',r.monthly_review_cost_inr],['False-positive review cost',r.monthly_false_positive_review_cost_inr],['Platform cost',r.monthly_platform_cost_inr]].map(([l,v])=>`<div class="execution-item"><span>${safe(l)}</span><b>${INR(v)}</b></div>`).join('')}</div><p class="note">${safe(r.disclaimer)}</p>`}catch(e){alert(e.message)}};
initialize();
